import "../recipes.just"

# -------
# CONFIG
# ------

MODEL := "/ds-models/DeepSeek-R1-0528-NVFP4-v2"
PREC := "fp4"
LYRIS_IFNAME := "enP22p3s0f1np1"
PTYCHE_IFNAME := "enP6p3s0f1np1"

# for 1K ISL 1K OSL
DECODE_NUM_SEQ := "1536"
# for 2K ISL 1K OSL
#DECODE_NUM_SEQ := "1220"
# for 2K ISL 2K OSL
#DECODE_NUM_SEQ := "1024"

# ---
# ENV
# ---

#NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME=enP22p3s0f1np1 \
#UCX_IB_ROCE_REACHABILITY_MODE=local_subnet \
#GLOO_SOCKET_IFNAME=enP22p3s0f1np1 \
#NCCL_SOCKET_IFNAME=enP22p3s0f1np1 \
#UCX_NET_DEVICES=eth0 \
#NCCL_DEBUG=INFO \
#NCCL_DEBUG_FILE=./nccl-debug-%h-%p.log \
SYSTEM_ENV := '''NVIDIA_GDRCOPY=1 \
NVSHMEM_IB_ENABLE_IBGDA=1 \
VLLM_SKIP_P2P_CHECK=1 \
NCCL_CUMEM_ENABLE=1 \
NCCL_MNNVL_ENABLE=1 \
NCCL_NVLS_ENABLE=1 '''


#VLLM_USE_TRTLLM_RAGGED_DEEPSEEK_PREFILL=1 \
COMMON_VLLM_ENV := '''\
VLLM_RANDOMIZE_DP_DUMMY_INPUTS=1 \
VLLM_USE_FLASHINFER_MOE_FP4=1 \
VLLM_FLASHINFER_MOE_BACKEND=latency \
VLLM_ENABLE_FUSED_MOE_ACTIVATION_CHUNKING=0 \
VLLM_USE_NCCL_SYMM_MEM=1 '''

# Currently there is no prefill or decode specific environment variables
PREFILL_VLLM_ENV := SYSTEM_ENV + COMMON_VLLM_ENV + '''\
VLLM_ENABLE_MOE_DP_CHUNK=0 ''' 

PREFILL_PD_VLLM_ENV := PREFILL_VLLM_ENV + PD_VLLM_ENV

DECODE_VLLM_ENV := SYSTEM_ENV + COMMON_VLLM_ENV + '''\
VLLM_LOG_STATS_INTERVAL=1 \
VLLM_MLA_FP8_PROJ=1 \
VLLM_DEEPEP_LOW_LATENCY_ALLOW_NVLINK=1 \
VLLM_DEEPEP_LOW_LATENCY_USE_MNNVL=1 \
VLLM_DEEPEP_BUFFER_SIZE_MB=0 \
VLLM_EP_USE_SBO=0 \
VLLM_MOE_DP_CHUNK_SIZE=''' + DECODE_NUM_SEQ + ''' \
VLLM_DEEPEPLL_NVFP4_DISPATCH=1 \
VLLM_ENABLE_FUSED_MOE_ACTIVATION_CHUNKING=0 \
VLLM_V1_OUTPUT_PROC_CHUNK_SIZE=2048 '''

DECODE_PD_VLLM_ENV := DECODE_VLLM_ENV + PD_VLLM_ENV

# ---------
# vLLM Args
# ---------

COMMON_VLLM_ARGS := '''
--profiler-config.torch_profiler_dir=./profile/ \
--attention-config.backend FLASHINFER_MLA \
--attention-config.use_trtllm_ragged_deepseek_prefill=true \
--kv-cache-dtype fp8 \
--enable-expert-parallel \
--data-parallel-rpc-port 13345 \
--max-model-len 2148 \
--disable-uvicorn-access-log \
--port 8088 \
--trust-remote-code \
--async-scheduling '''

#--compilation_config.custom_ops+=+quant_fp8,+rms_norm,+rotary_embedding \
PREFILL_VLLM_ARGS := COMMON_VLLM_ARGS + '''\
--disable_custom_all_reduce \
--disable_nccl_for_dp_synchronization \
--no-enable-prefix-caching \
--all2all-backend allgather_reducescatter \
--gpu-memory-utilization 0.85 \
--max-num-batched-tokens 65536 \
--max-num-seqs 1024 \
--swap-space 16 \
--data-parallel-size 2 \
--enforce-eager \
--offload-group-size 2 \
--offload-num-in-group 1 \
--offload-prefetch-step 1 \
 '''

PREFILL_PD_VLLM_ARGS := PREFILL_VLLM_ARGS + PD_VLLM_ARGS

DECODE_VLLM_ARGS := COMMON_VLLM_ARGS + '''\
--all2all-backend allgather_reducescatter \
--compilation-config.cudagraph_mode FULL_DECODE_ONLY \
--compilation_config.custom_ops+=+rms_norm,+rotary_embedding \
--data-parallel-hybrid-lb \
--kv_cache_memory_bytes 117019622533 \
--data-parallel-size-local 4 \
--stream-interval 50 \
--max-num-seqs ''' + DECODE_NUM_SEQ + ''' \
--max-num-batched-tokens ''' + DECODE_NUM_SEQ + ''' \
--cudagraph-capture-sizes 128 512 ''' + DECODE_NUM_SEQ + " "

DECODE_PD_VLLM_ARGS := DECODE_VLLM_ARGS + PD_VLLM_ARGS
